local text_original = LocalizationManager.text
function LocalizationManager:text(string_id, ...)
return string_id == "all_2" and "Helmet Popping"
or string_id =="all_2_desc" and "Increases your headshot damage by ##25%##."
or string_id =="all_4" and "Blending In"
or string_id =="all_4_desc" and "You gain ##+1## increased concealment.\n\nWhen wearing armor, your movement speed is ##15%## less affected. \n\nYou gain ##45%## more experience when you complete days and jobs."
or string_id =="all_6" and "Walk-in Closet"
or string_id =="all_6_desc" and "Unlocks an armor bag equipment for you to use. The armor bag can be used to change your armor during a heist.\n\nIncreases your ammo pickup to ##135%## of the normal rate. "
or string_id =="all_8" and "Fast And Furious"
or string_id =="all_8_desc" and "You deal ##5%## more damage.\n\nIncreases your doctor bag interaction speed by ##20%##. "

or string_id == "Clockwork_title" and "ClockWork"
or string_id == "Clockwork_desc" and "Keep the tempo to stay alive/n/nDrop the tempo and feel pain, lots of pain and sadness"
or string_id == "Clockwork_1" and "Tempo"
or string_id == "Clockwork_1_desc" and "##Lose 99% Health on mission start##\n##Does NOT show on inventory stats screen##\nArmor Regen is changed to be ##30## seconds without skills\n\nGain ##60## armor for each kill\nCooldown is ##2## Seconds"
or string_id == "Clockwork_3" and "Tick Tock"
or string_id == "Clockwork_3_desc" and "Gain ##75%## armor\nTotal bonus armor is ##75%##"
or string_id == "Clockwork_5" and "Pocket Metronome"
or string_id == "Clockwork_5_desc" and "Gain ##25%## armor\nTotal bonus armor is ##100%##\n\nGain ##80## armor for each kill\nCooldown is ##2## Seconds"
or string_id == "Clockwork_7" and "Metal Parts"
or string_id == "Clockwork_7_desc" and "Gain ##25%## armor\nTotal bonus armor is ##125%##"
or string_id == "Clockwork_9" and "Orange Paint"
or string_id == "Clockwork_9_desc" and "Gain ##25%## armor\nTotal bonus armor is ##150%##\n\nGain ##100## armor for each kill\nCooldown is ##2## Seconds\n\nDeck Completion Bonus: Your chance of getting a higher quality item during a PAYDAY is increased by ##10%##"

or string_id == "Mafia_title" and "Mafia"
or string_id == "Mafia_desc" and "A deck centered around buffing frenzy for a unique style of bezerker"
or string_id == "Mafia_1" and "Call Me Big Tony"
or string_id == "Mafia_1_desc" and "Gain ##50%## bonus armor\nTotal bonus armor is ##50%##"
or string_id == "Mafia_3" and "Additional padding"
or string_id == "Mafia_3_desc" and "Gain ##25%## bonus armor\nTotal bonus armor is ##75%##"
or string_id == "Mafia_5" and "Lightweight Kevlar"
or string_id == "Mafia_5_desc" and "Gain ##25%## bonus armor\nTotal bonus armor is ##100%##Gain ##30%## bonus movement speed in armor"
or string_id == "Mafia_7" and "Custom Ordered Kevlar"
or string_id == "Mafia_7_desc" and "Gain ##40%## bonus movement speed in armor"
or string_id == "Mafia_9" and "Kevlar From Bain"
or string_id == "Mafia_9_desc" and "Gain ##50%## bonus movement speed in armor\n\nLoot bag movement penalty is reduced by ##25%##"

or string_id == "Maso_title" and "Masochist"
or string_id == "Maso_desc" and "The health version of Anarchist perk deck\n\n\Armor perks from skills and other crew members perk decks that affect total armor have ##NO## effect While using this perk deck!\nArmor Recovery perks however do still work\n\nNote: Crew perks do not stack"
or string_id == "Maso_1" and "The Pain Goes Here"
or string_id == "Maso_1_desc" and "##Lose all armor##\n\nGain ##33%## health\nTotal bonus health is ##133%##"
or string_id == "Maso_3" and "That All You Got"
or string_id == "Maso_3_desc" and "Regenerate ##5%## health per ##4## seconds"
or string_id == "Maso_5" and "Are You Even Trying"
or string_id == "Maso_5_desc" and "Gain ##33%## health\nTotal bonus health is ##166%##"
or string_id == "Maso_7" and "No Do It Like This"
or string_id == "Maso_7_desc" and "Regenerate ##10%## health per ##4## seconds"
or string_id == "Maso_9" and "And Some For You And You And You"
or string_id == "Maso_9_desc" and "Gain ##33%## health\nTotal bonus health is ##200%##\n\nRegenerate ##15%## health per ##4## seconds\n\nDeck Completion Bonus: Your chance of getting a higher quality item during a PAYDAY is increased by ##10%##"

or string_id == "Greed_title" and "Greed"
or string_id == "Greed_desc" and "Trade skills for more value to bagged loot such as meth,paintings,coke,etc.\nBonus cash is only for extra mission bags such as paintings in FFD1, coke in ratsD1/cookoff and the like"
or string_id == "Greed_1" and "Teach Bain Economics"
or string_id == "Greed_1_desc" and "Gain ##25%## bonus XP\n\nTotal Bonus XP is ##25%##"
or string_id == "Greed_3" and "Gold Plated Silver"
or string_id == "Greed_3_desc" and "Gain ##25%## bonus Cash\n\nTotal Bonus Cash is ##25%##"
or string_id == "Greed_5" and "See-Thru Metal"
or string_id == "Greed_5_desc" and "Gain ##25%## bonus XP\nGain ##25%## bonus Cash\n\nTotal Bonus XP is ##50%##\nTotal Bonus Cash is ##50%##"
or string_id == "Greed_7" and "Gold Plated Gold"
or string_id == "Greed_7_desc" and "Gain ##25%## bonus XP\n\nTotal Bonus XP is ##75%##"
or string_id == "Greed_9" and "Why Don't We Just Charge More?"
or string_id == "Greed_9_desc" and "Gain ##25%## bonus XP\nGain ##25%## bonus Cash\n\nTotal Bonus XP is ##100%##\nTotal Bonus Cash is ##75%##\n\nGain ##25%##speed after securing a lootbag\n\nDeck Completion Bonus: Your chance of getting a higher quality item during a PAYDAY is increased by ##10%##"

or string_id == "Junkie_title" and "Ammo Junkie"
or string_id == "Junkie_desc" and "Need more bullets? how about your crew?"
or string_id == "Junkie_1" and "Deep Pockets"
or string_id == "Junkie_1_desc" and "Pickup ##10%## more bullets from dropped ammo\n\nTotal ammo pickup is +##10%##"
or string_id == "Junkie_3" and "Vendor"
or string_id == "Junkie_3_desc" and "Pickup ##15%## more bullets from dropped ammo\n\nTotal ammo pickup is +##25%##\n\nCarry ##10%## more total ammo\n\nTotal bonus max ammo is ##10%##\n\nWhen you pick up ammo, your team receives ##50%## ammo, Vendor cooldown is ##5## seconds"
or string_id == "Junkie_5" and "Makeshift Rounds"
or string_id == "Junkie_5_desc" and "Pickup ##15%## more bullets from dropped ammo\n\nTotal ammo pickup is +##40%##\n\nCarry ##5%## bonus total ammo\n\nTotal bonus max ammo is ##15%##"
or string_id == "Junkie_7" and "Duct Tape And Bullets"
or string_id == "Junkie_7_desc" and "Pickup ##15%## more bullets from dropped ammo\n\nTotal ammo pickup is +##55%##\n\nCarry ##5%## bonus total ammo\n\nTotal bonus max ammo is ##20%##\n\nAmmo pickup radius increased by ##25%##"
or string_id == "Junkie_9" and "Rounds From Wallmart"
or string_id == "Junkie_9_desc" and "Vendor Cooldown is Removed\n\nVendor now gies ##100%## ammo to teammates\n\nDeck Completion Bonus: Your chance of getting a higher quality item during a PAYDAY is increased by ##10%##"

or string_id == "Mw2_title" and "Marathon"
or string_id == "Mw2_desc" and "What the fuck are you doing? cant stop running!"
or string_id == "Mw2_1" and "I Need Marathon pro"
or string_id == "Mw2_1_desc" and "Recover Stamina ##50%## faster from running/jumping"
or string_id == "Mw2_3" and "Marathon pro"
or string_id == "Mw2_3_desc" and "Recover Stamina ##75%## faster from running/jumping"
or string_id == "Mw2_5" and "Marathon pro"
or string_id == "Mw2_5_desc" and "Recover Stamina ##100%## faster from running/jumping\n\nRecover stamina at a ##150%## rate\n\nLoot bag movement penalty is reduced by ##25%##"
or string_id == "Mw2_7" and "Marathon pro"
or string_id == "Mw2_7_desc" and "Recover stamina at a ##175%## rate\nGain ##250%## total stamina"
or string_id == "Mw2_9" and "Great Now I Gotta Get Sitrep pro..."
or string_id == "Mw2_9_desc" and "Recover Stamina ##immediately## from running/jumping\nGain ##300%## total stamina\n##Fall Damage is Removed from NON FATAL FALLS##\n\nLoot bag movement penalty is reduced by ##50%##\n\nDeck Completion Bonus: Your chance of getting a higher quality item during a PAYDAY is increased by ##10%##"

or string_id == "Blood_title" and "Blood Rage"
or string_id == "Blood_desc" and "Whats a Bloodrage? and why don't I remember anything?"
or string_id == "Blood_1" and "You Gotta Try This"
or string_id == "Blood_1_desc" and "Armor Regen is changed to be ##400## Seconds without perks\n\nSteal ##10%## Blood from melee strikes\n\nCooldown is ##6## Seconds"
or string_id == "Blood_3" and "Bang Bang Bang Bang"
or string_id == "Blood_3_desc" and "Steal ##10%## Blood from melee strikeshit\n\nCooldown is ##3## Seconds\n\nGain ##150%## Blood"
or string_id == "Blood_5" and "This Is Addicting"
or string_id == "Blood_5_desc" and "Steal ##10%## Blood from melee strikes\n\nCooldown is ##1.5## Seconds\n\nGain ##200%## Blood"
or string_id == "Blood_7" and "Blood Soaked Shields"
or string_id == "Blood_7_desc" and "Steal ##10%## Blood from melee strikes\n\nCooldown is ##Removed##\n\nGain ##250%## Blood\n\nGain ##100## Blood Shield Per Fallen\nCooldown is ##2## Seconds"
or string_id == "Blood_9" and "Blood Soaked Blood"
or string_id == "Blood_9_desc" and "Steal ##20%## Blood from melee strikes\n\nCooldown is ##Removed##\n\nGain ##100%## more Blood Shield\n\nDeck Completion Bonus: Your chance of getting a higher quality item during a PAYDAY is increased by ##10%##"

or string_id == "Casino_title" and "High Roller"
or string_id == "Casino_desc" and "High Dodge Low survivability"
or string_id == "Casino_1" and "Roulette"
or string_id == "Casino_1_desc" and "loose ##50%## armor and health\n\nGain ##12## dodge chance\nTotal dodge chance is ##12##"
or string_id == "Casino_3" and "Blackjack"
or string_id == "Casino_3_desc" and "Gain ##12## dodge chance\nTotal dodge chance is ##24##"
or string_id == "Casino_5" and "Poker Skills"
or string_id == "Casino_5_desc" and "Gain ##12## dodge chance\nTotal dodge chance is ##36##"
or string_id == "Casino_7" and "Jackpot"
or string_id == "Casino_7_desc" and "Gain ##12## dodge chance\nTotal dodge chance is ##48##"
or string_id == "Casino_9" and "Why is darts in a casino?"
or string_id == "Casino_9_desc" and "Gain ##12## dodge chance\nTotal dodge chance is ##60##\n\nDeck Completion Bonus: Your chance of getting a higher quality item during a PAYDAY is increased by ##10%##"

or text_original(self, string_id, ...)
end